Update patch set 3
Patch Set 3: Code-Review-1

I can query stuff now, which is good.

I don't see any man page updates for the new functionality which makes testing difficult.

I don't see a ticket for updating pupmod, which throws the error:

Error: /Stage[main]/Pupmod::Master::Base/Puppet_auth[puppetlast_support]: Could not evaluate: undefined method `chomp' for #<Hash:0x000000052c13e8>

Patch-set: 3
Label: Code-Review=-1