Update patch set 1
Patch Set 1:

> repoclosure failed during a clean build:auto from 4.2.X:
 > 
 > rake aborted!
 > Error: REPOCLOSURE FAILED:
 > Skipping unreadable repository '/etc/yum.repos.d/virtualbox.repo'
 > Reading in repository metadata - please wait....
 > Checking Dependencies
 > Repos looked at: 2
 > base
 > lookaside
 > Num Packages in Repos: 1755
 > package: pupmod-simp-freeradius-5.0.2-2016.noarch from base
 > unresolved deps:!
 > pupmod-simp-openldap >= 0:4.1.0-3
 > package: pupmod-simp-nscd-5.0.1-2016.noarch from base
 > unresolved deps:!
 > pupmod-simp-openldap >= 0:4.1.0-3
 > package: pupmod-simp-simp-1.2.7-2016.noarch from base
 > unresolved deps:!
 > pupmod-simp-openldap >= 0:4.1.4-0
 > package: pupmod-simp-stunnel-4.2.7-2016.noarch from base
 > unresolved deps:!
 > pupmod-simp-openldap >= 0:2.0.0-0
 > /home/chris/.rvm/gems/ruby-2.0.0-p643/gems/simp-rake-helpers-2.4.6/lib/simp/rake/build/pkg.rb:567:in
 > `block (3 levels) in define_tasks'

This failure doesn't have anything to do with the change that was made.

Patch-set: 1
Reviewer: Trevor Vaughan <1004834@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Code-Review=0