(SIMP-5092) Remove `gem install` from nodesets
Before this patch, fresh container builds of the simp-core beaker suite
rpm_docker would fail with:

```
ERROR:  Error installing simp-rake-helpers:
    The last version of net-telnet (>= 0) to support your Ruby & RubyGems was 0.1.1. Try installing it with `gem install net-telnet -v 0.1.1` and then running the current command again
    net-telnet requires Ruby version >= 2.3.0. The current ruby version is 2.1.0.
```

The `Gemfile.lock` in simp-core already pins `net-telnet` to 0.1.1. However,
the rpm_docker nodesets naively attempt to install simp-rake-helpers before the
tests without bundler, which fetches the latest (and incompatible) net-telnet
as a dependency.

To prevent future dependency problems, this patch removes the unpinned `gem
install` lines from the `rpm_docker` nodesets and runs bundler using the
existing `Gemfile.lock` to fetch all dependencies (as it was designed to do).

SIMP-5092 #close